version: "3"

volumes:
  postgres_data: {}
  pgadmin_data: {}

networks:
  postgres:
    driver: bridge

services:
  postgres:
    container_name: scala-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: scala-pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - postgres
